include ../../maker/envCom.mk
# Source and build directories
PROJECT := mspprofiler
SRC_DIR := src
BLD_DIR := build
LIB_DIR := ..

# Uncomment if additional flags or includes are needed
# (other than the ones defined in maker/libs.mk)
INCLUDES := \
	-I $(LIB_DIR)/mspDebugger/include \

# CFLAGS :=

include ../../maker/libs.mk
